{
 "title": "Default",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dançabilidade por gênero",
   "type": "barchart",
   "description": "Dançabilidade descreve o quão adequada uma faixa é para dançar com base em uma combinação de elementos musicais, incluindo andamento, estabilidade de ritmo, força de batida e regularidade geral. \n\nUm valor de 0.0 é menos dançante e 1.0 é mais dançante.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(danceability) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Energia por gênero",
   "type": "barchart",
   "description": "Energia é um valor de 0.0 a 1.0 que representa uma medida perceptiva de intensidade e atividade. \n\nNormalmente, as faixas energéticas parecem rápidas, altas e barulhentas. Por exemplo, o death metal tem alta energia, enquanto um prelúdio de Bach tem pontuação baixa na escala. As características perceptivas que contribuem para este atributo incluem faixa dinâmica, volume percebido, timbre, taxa de início e entropia geral.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(energy) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Tom por gênero",
   "type": "barchart",
   "description": "A tonalidade em que a faixa está. Os números inteiros são mapeados para tons usando a notação padrão de classe de tom. \n\nPor exemplo 0 = C, 1 = C♯/D♭, 2 = D e assim por diante.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(key) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Volume geral por gênero",
   "type": "barchart",
   "description": "A intensidade sonora geral de uma faixa em decibéis (dB). Os valores de intensidade sonora são calculados em média em toda a faixa e são úteis para comparar a intensidade sonora relativa das faixas. A intensidade sonora é a qualidade de um som que é o principal correlato psicológico da força física (amplitude). \n\nOs valores geralmente variam entre -60 e 0 db.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(loudness) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Modo por gênero",
   "type": "barchart",
   "description": "Modo indica a modalidade (maior ou menor) de uma faixa, o tipo de escala da qual deriva seu conteúdo melódico. \n\nMaior é representado por 1 e menor é 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(mode) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Falabilidade por gênero",
   "type": "barchart",
   "description": "Falabilidade detecta a presença de palavras faladas em uma faixa. Quanto mais exclusivamente falada for a gravação (por exemplo, talk show, audiolivro, poesia), mais próximo de 1.0 será o valor do atributo. Valores acima de 0.66 descrevem faixas que provavelmente são compostas inteiramente de palavras faladas. \n\nValores entre 0.33 e 0.66 descrevem faixas que podem conter música e fala, seja em seções ou em camadas, incluindo casos como música rap. Valores abaixo de 0.33 provavelmente representam música e outras faixas não faladas.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(speechiness) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Acusticidade por gênero",
   "type": "barchart",
   "description": "Uma medida de confiança de 0.0 a 1.0 para saber se a faixa é acústica. \n\n1.0 representa alta confiança de que a faixa é acústica.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(acousticness) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Instrumentabilidade por gênero",
   "type": "barchart",
   "description": "Prevê se uma faixa não contém vocais. Os sons \"Ooh\" e \"aah\" são tratados como instrumentais neste contexto. Faixas de rap ou palavras faladas são claramente \"vocais\". Quanto mais próximo o valor da instrumentalidade estiver de 1.0, maior será a probabilidade de a faixa não conter conteúdo vocal. \n\nValores acima de 0.5 pretendem representar faixas instrumentais, mas a confiança é maior à medida que o valor se aproxima de 1.0.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(instrumentalness) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Vivacidade por gênero",
   "type": "barchart",
   "description": "Detecta a presença de público na gravação. Valores mais altos de vivacidade representam uma probabilidade maior de que a faixa tenha sido tocada ao vivo. \n\nUm valor acima de 0.8 oferece forte probabilidade de que a faixa seja ao vivo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(liveness) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  },
  {
   "title": "Valência por gênero",
   "type": "barchart",
   "description": "Uma medida de 0.0 a 1.0 que descreve a positividade musical transmitida por uma faixa. \n\nFaixas com alta valência soam mais positivas (por exemplo, feliz, alegre, eufórica), enquanto faixas com baixa valência soam mais negativas (por exemplo, triste, deprimida, irritada).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(valence) FROM df_tracks GROUP BY genre ORDER BY genre LIMIT 50 "
    }
   ]
  }
 ]
}