# -*- coding: utf-8 -*-
"""playlist_features_extractor_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nu9sKaRzZj8ou9z2noeO-ciqsl5zh1N6
"""

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from google.colab import files

client_id = '0dba842d359e48b9be6523154f3df372'
client_secret = '8032d41cbfa14674ac9d45ac0a823331'

client_credentials_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

playlists_genero = {
    'pagode': '37i9dQZF1DXchBFvKSUooB',
    'classica': '37i9dQZF1DWTi57LiHYTmH',
    'rock': '37i9dQZF1DWXRqgorJj26U',
    'pop': '37i9dQZF1DX9VAqVAZ6EMr',
    'rap': '37i9dQZF1DWYok9l1JL7GM',
    'edm': '37i9dQZF1DX3Kdv0IChEm9'
}

for genero, playlist_id in playlists_genero.items():
    results = sp.playlist_tracks(playlist_id)
    file_path = f'{genero}_playlist_features.txt'

    with open(file_path, 'w') as file:
        for track in results['items']:
            track_id = track['track']['id']
            features = sp.audio_features(track_id)

            file.write(str(features) + '\n')

    print(f"Features da playlist de {genero} foram salvas em {file_path}")

zip_file_path = 'playlist_features.zip'
!zip $zip_file_path *_playlist_features.txt

files.download(zip_file_path)
