{
 "title": "Default",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "top_rankings_limit", "label": "TOP", "query": "5,10,25,50,100" },
   {
    "name": "ranking_genres",
    "label": "Gênero",
    "query": "classica,edm,pagode,pop,rap,rock"
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Artistas com músicas mais dançantes",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking dos $top_rankings_limit artistas com maior média de dançabilidade no(s) gênero(s) selecionado(s). O painel também agrupa a música mais dançante de cada artista listado.\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"artist_name\">{{artist_name}}</p>\n  <div class=\"icon\" id=\"track_icon\"></div>\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "WITH ArtistFeatureTop AS (\r\n  SELECT\r\n    a.artist_name,\r\n    at.track_id,\r\n    t.danceability,\r\n    ROW_NUMBER() OVER (\r\n      PARTITION BY a.artist_name\r\n      ORDER BY\r\n        t.danceability DESC\r\n    ) AS rank\r\n  FROM\r\n    artists a\r\n    JOIN artist_track at ON a.artist_id = at.artist_id\r\n    JOIN tracks t ON at.track_id = t.track_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nArtistFeatureAvg AS (\r\n  SELECT\r\n    a.artist_name,\r\n    AVG(t.danceability) AS feature\r\n  FROM\r\n    artists a\r\n    JOIN artist_track at ON a.artist_id = at.artist_id\r\n    JOIN tracks t ON at.track_id = t.track_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n  GROUP BY\r\n    a.artist_name\r\n),\r\nTopArtists AS (\r\n  SELECT\r\n    aft.artist_name,\r\n    aft.track_id,\r\n    afa.feature\r\n  FROM\r\n    ArtistFeatureTop aft\r\n    JOIN ArtistFeatureAvg afa ON aft.artist_name = afa.artist_name\r\n  WHERE\r\n    aft.rank = 1\r\n  ORDER BY\r\n    afa.feature DESC\r\n  LIMIT\r\n    $top_rankings_limit\r\n)\r\n\r\nSELECT\r\n  t.track_id,\r\n  t.preview_url,\r\n  t.track_name,\r\n  a.album_name,\r\n  ar.artist_name,\r\n  (\r\n    SELECT\r\n      i.url\r\n    FROM\r\n      image_track it\r\n      JOIN images i ON it.image_id = i.image_id\r\n    WHERE\r\n      it.track_id = t.track_id\r\n    ORDER BY\r\n      i.height DESC\r\n    LIMIT\r\n      1\r\n  ) AS image_url\r\nFROM\r\n  tracks t\r\n  JOIN album a ON t.album_id = a.album_id\r\n  JOIN artist_track at ON t.track_id = at.track_id\r\n  JOIN artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n  t.track_id IN (\r\n    SELECT\r\n      track_id\r\n    FROM\r\n      TopArtists\r\n  )\r\nGROUP BY\r\n  t.track_id,\r\n  t.track_name,\r\n  a.album_name,\r\n  ar.artist_name\r\nORDER BY\r\n  t.danceability DESC"
      }
     ]
    },
    {
     "title": "Artistas com músicas mais dançantes",
     "type": "table",
     "description": "Ranking dos $top_rankings_limit artistas com maior média de dançabilidade no(s) gênero(s) selecionado(s).",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.danceability\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(danceability) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
      }
     ]
    }
   ]
  },
  {
   "title": "Rankings - Músicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Músicas mais dançantes",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de dançabilidade no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>\n"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.danceability DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas mais enérgicas",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de energia no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.energy DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas mais acústicas",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de acusticidade no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.acousticness DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas com maior falabilidade",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de falabilidade no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.speechiness DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas com maior vivacidade",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de vivacidade no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.liveness DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas mais instrumentais",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de instrumentabilidade no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.instrumentalness DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas com maior valência",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de valência no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.valence DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas com maior volume geral",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de volume geral no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.loudness DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    },
    {
     "title": "Músicas com maior tempo musical",
     "type": "marcusolsson-dynamictext-panel",
     "description": "Ranking das $top_rankings_limit músicas com maior métrica de tempo musical no(s) gênero(s) selecionado(s).\n\nClique na capa do álbum para ampliar, ou no título da música para reproduzir/pausar uma prévia (se disponível).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "options": {
      "content": "<div class=\"cover\" style=\"background-image: url({{image_url}})\" onclick=\"openNewTab('{{image_url}}')\"></div>\n<div id=\"content\">\n  <p class=\"details\" id=\"track_name\" onclick=\"playOrPause('{{preview_url}}')\">{{track_name}}</p>\n  <div class=\"icon\" id=\"artist_icon\"></div>\n  <p class=\"details\" id=\"artists_name\">{{artist_names}}</p>\n  <div class=\"icon\" id=\"album_icon\"></div>\n  <p class=\"details\" id=\"album_name\">{{album_name}}</p>\n</div>"
     },
     "targets": [
      {
       "rawSql": "SELECT \r\n    t.track_id,\r\n    t.preview_url,\r\n    t.track_name, \r\n    a.album_name, \r\n    STRING_AGG(DISTINCT ar.artist_name, ', ') AS artist_names,\r\n    (\r\n        SELECT i.url\r\n        FROM image_track it\r\n        JOIN images i ON it.image_id = i.image_id\r\n        WHERE it.track_id = t.track_id\r\n        ORDER BY i.height DESC\r\n        LIMIT 1\r\n    ) AS image_url\r\nFROM \r\n    tracks t\r\nJOIN \r\n    album a ON t.album_id = a.album_id\r\nJOIN \r\n    artist_track at ON t.track_id = at.track_id\r\nJOIN \r\n    artists ar ON at.artist_id = ar.artist_id\r\nWHERE\r\n    t.genre IN ($ranking_genres)\r\nGROUP BY \r\n    t.track_id, t.track_name, a.album_name\r\nORDER BY \r\n    t.tempo DESC\r\nLIMIT $top_rankings_limit;\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Rankings - Artistas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Artistas com músicas mais dançantes",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de dançabilidade no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.danceability\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(danceability) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas mais enérgicas",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de energia no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.energy\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(energy) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas mais acústicas",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de acusticidade no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.acousticness\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(acousticness) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas de maior falabilidade",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de falabilidade no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.acousticness\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(acousticness) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas de maior vivacidade",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de vivacidade no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.liveness\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(liveness) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas mais instrumentais",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de instrumentabilidade no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.instrumentalness\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(instrumentalness) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas de maior valência",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de valência no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.valence\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(valence) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas de maior volume geral",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de volume geral no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.loudness\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(loudness) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  {
   "title": "Artistas com músicas de maior tempo musical",
   "type": "table",
   "description": "Ranking dos $top_rankings_limit artistas com maior média de tempo musical no(s) gênero(s) selecionado(s).",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH track_artist_feature AS (\r\n  SELECT \r\n    t.track_id,\r\n    at.artist_id,\r\n    a.artist_name,\r\n    t.tempo\r\n  FROM \r\n    tracks t\r\n  JOIN \r\n    artist_track at ON t.track_id = at.track_id\r\n  JOIN \r\n    artists a ON at.artist_id = a.artist_id\r\n  WHERE\r\n    t.genre IN ($ranking_genres)\r\n),\r\nartist_avg_feature AS (\r\n  SELECT \r\n    artist_name,\r\n    AVG(tempo) AS avg_feature\r\n  FROM \r\n    track_artist_feature\r\n  GROUP BY \r\n    artist_name\r\n)\r\nSELECT \r\n  artist_name\r\nFROM \r\n  artist_avg_feature\r\nORDER BY \r\n  avg_feature DESC\r\nLIMIT $top_rankings_limit;"
    }
   ]
  },
  { "title": "Médias gerais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Dançabilidade por gênero",
   "type": "barchart",
   "description": "Dançabilidade descreve o quão adequada uma faixa é para dançar com base em uma combinação de elementos musicais, incluindo andamento, estabilidade de ritmo, força de batida e regularidade geral. \n\nUm valor de 0.0 é menos dançante e 1.0 é mais dançante.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(danceability) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Energia por gênero",
   "type": "barchart",
   "description": "Energia é um valor de 0.0 a 1.0 que representa uma medida perceptiva de intensidade e atividade. \n\nNormalmente, as faixas energéticas parecem rápidas, altas e barulhentas. Por exemplo, o death metal tem alta energia, enquanto um prelúdio de Bach tem pontuação baixa na escala. As características perceptivas que contribuem para este atributo incluem faixa dinâmica, volume percebido, timbre, taxa de início e entropia geral.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(energy) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Acusticidade por gênero",
   "type": "barchart",
   "description": "Uma medida de confiança de 0.0 a 1.0 para saber se a faixa é acústica. \n\n1.0 representa alta confiança de que a faixa é acústica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(acousticness) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Falabilidade por gênero",
   "type": "barchart",
   "description": "Falabilidade detecta a presença de palavras faladas em uma faixa. Quanto mais exclusivamente falada for a gravação (por exemplo, talk show, audiolivro, poesia), mais próximo de 1.0 será o valor do atributo. Valores acima de 0.66 descrevem faixas que provavelmente são compostas inteiramente de palavras faladas. \n\nValores entre 0.33 e 0.66 descrevem faixas que podem conter música e fala, seja em seções ou em camadas, incluindo casos como música rap. Valores abaixo de 0.33 provavelmente representam música e outras faixas não faladas.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(speechiness) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Vivacidade por gênero",
   "type": "barchart",
   "description": "Detecta a presença de público na gravação. Valores mais altos de vivacidade representam uma probabilidade maior de que a faixa tenha sido tocada ao vivo. \n\nUm valor acima de 0.8 oferece forte probabilidade de que a faixa seja ao vivo.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(liveness) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Instrumentabilidade por gênero",
   "type": "barchart",
   "description": "Prevê se uma faixa não contém vocais. Os sons \"Ooh\" e \"aah\" são tratados como instrumentais neste contexto. Faixas de rap ou palavras faladas são claramente \"vocais\". Quanto mais próximo o valor da instrumentalidade estiver de 1.0, maior será a probabilidade de a faixa não conter conteúdo vocal. \n\nValores acima de 0.5 pretendem representar faixas instrumentais, mas a confiança é maior à medida que o valor se aproxima de 1.0.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(instrumentalness) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Valência por gênero",
   "type": "barchart",
   "description": "Uma medida de 0.0 a 1.0 que descreve a positividade musical transmitida por uma faixa. \n\nFaixas com alta valência soam mais positivas (por exemplo, feliz, alegre, eufórica), enquanto faixas com baixa valência soam mais negativas (por exemplo, triste, deprimida, irritada).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(valence) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Volume geral por gênero",
   "type": "barchart",
   "description": "A intensidade sonora geral de uma faixa em decibéis (dB). Os valores de intensidade sonora são calculados em média em toda a faixa e são úteis para comparar a intensidade sonora relativa das faixas. A intensidade sonora é a qualidade de um som que é o principal correlato psicológico da força física (amplitude). \n\nOs valores geralmente variam entre -60 e 0 db.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(loudness) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Tempo por gênero",
   "type": "barchart",
   "description": "O tempo estimado geral de uma faixa em batidas por minuto (BPM). \n\nNa terminologia musical, o tempo é a velocidade ou o ritmo de uma determinada peça e deriva diretamente da duração média da batida.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(tempo) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Tom por gênero",
   "type": "barchart",
   "description": "A tonalidade em que a faixa está. Os números inteiros são mapeados para tons usando a notação padrão de classe de tom. \n\nPor exemplo 0 = C, 1 = C♯/D♭, 2 = D e assim por diante.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(key) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Modo por gênero",
   "type": "barchart",
   "description": "Modo indica a modalidade (maior ou menor) de uma faixa, o tipo de escala da qual deriva seu conteúdo melódico. \n\nMaior é representado por 1 e menor é 0.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(mode) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  },
  {
   "title": "Assinatura de tempo por gênero",
   "type": "barchart",
   "description": "Uma assinatura de tempo estimada. A assinatura de tempo (metro) é uma convenção de notação para especificar quantas batidas há em cada compasso (ou medida). \n\nA assinatura de tempo varia de 3 a 7, indicando assinaturas de tempo de \"3/4\" a \"7/4\".",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT genre, AVG(time_signature) FROM tracks GROUP BY genre ORDER BY genre "
    }
   ]
  }
 ]
}